#!/usr/bin/env python3
"""Build Table 1 (detection rates) pooled across all benchmark years.

Each (budget, strategy) cell pools the per-fire rows from every benchmark year
(2021–2024) and reports the overall detection rate with a 95% Wilson score
interval, the within-1h share (Delta t = 0), the mean detection delay over
detected fires, and the pooled fire count. Detection rates and confidence
intervals are computed over the full pooled fire population (each fire is one
trial), not by averaging per-year percentages.

Reuses the canonical CSV specs and routing aggregation from
``paper/final_report/generate_final_report.py`` so the table, the markdown
report (§2), and Figure 3 stay numerically identical.

Run from the project root:
    python paper/Nature_Wildfires/scripts/build_table1_detection.py
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "paper" / "final_report"))

from generate_final_report import (  # noqa: E402
    ROUTING_CSV_SPECS,
    ROUTING_YEARS,
    load_rows_multi,
    routing_block,
)

OUT_PATH = REPO / "paper" / "Nature_Wildfires" / "table1_detection.tex"

BUDGET_ORDER = [20, 50, 75, 100, 500]


def _fmt_det(p: float, ci: tuple[float, float] | None) -> str:
    if ci is None:
        return f"{100 * p:.1f}"
    return f"{100 * p:.1f} [{100 * ci[0]:.1f}, {100 * ci[1]:.1f}]"


def build_table() -> None:
    # budget -> ordered list of (strategy, stats)
    cells: dict[int, list[tuple[str, dict]]] = {b: [] for b in BUDGET_ORDER}
    for budget, strat, _mode, paths in ROUTING_CSV_SPECS:
        rows = load_rows_multi(paths)
        # n_disc only affects the (unused) among-discoverable column; pass 0.
        cells[budget].append((strat, routing_block(rows, 0)))

    yr = f"{ROUTING_YEARS[0]}\\textendash{ROUTING_YEARS[-1]}"
    n_values = sorted({st["n"] for col in cells.values() for _s, st in col})
    n_label = (
        f"{n_values[0]:,}" if len(n_values) == 1 else f"{min(n_values):,}\\textendash{max(n_values):,}"
    )

    lines: list[str] = [
        f"% Table 1 — Detection rates across strategies and budgets ({ROUTING_YEARS[0]}–{ROUTING_YEARS[-1]}, pooled over all fires)",
        "% Generated by paper/Nature_Wildfires/scripts/build_table1_detection.py",
        "% Pooled per-fire across years (75M: 20260522_170454; 500M eps1 + T20 ground-sensor opt-cell fix: 20260523_212551_sensorfix; others: 20260520_062339)",
        "% Confidence intervals: 95% Wilson score interval on the pooled fire population",
        "\\begin{table}[!t]",
        "\\caption{Detection performance across routing strategies and deployment budgets,",
        f"  pooled over California wildfire years {yr} (\\(n = {n_label}\\) fires per cell).",
        "  Rates are computed over the full pooled fire population, not by averaging per-year rates.",
        "  \\emph{Det.\\ rate}: overall detection rate with 95\\% Wilson score interval.",
        "  \\emph{Within 1\\,h}: share of all fires detected in the first simulation step (\\(\\Delta t = 0\\)).",
        "  \\emph{Mean $\\Delta t$}: mean detection delay (hours) over detected fires only.}",
        "\\label{tab:detection}",
        "\\begin{tabular}{@{}llrrrr@{}}",
        "\\toprule",
        "Budget & Strategy & Det.\\ rate (\\%) & Within 1\\,h (\\%) & Mean $\\Delta t$ (h) & $n$ fires \\\\",
        "\\midrule",
    ]

    for bi, budget in enumerate(BUDGET_ORDER):
        for si, (strat, st) in enumerate(cells[budget]):
            det = _fmt_det(st["p"], st["ci_p"])
            w1h = f"{100 * st['within1h_p']:.1f}"
            mdt = "---" if math.isnan(st["mean_dt"]) else f"{st['mean_dt']:.2f}"
            budget_cell = f"\\${budget}M" if si == 0 else ""
            lines.append(
                f"{budget_cell} & {strat:<14} & {det} & {w1h} & {mdt} & {st['n']} \\\\"
            )
        if bi != len(BUDGET_ORDER) - 1:
            lines.append("\\addlinespace")

    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH} ({len(lines)} lines)")
    print(f"Years pooled: {ROUTING_YEARS}; n per cell: {n_label}")


if __name__ == "__main__":
    build_table()
