name: wf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=25.2
  - numpy=2.2
  - pandas=2.3
  - matplotlib=3.10
  - scipy=1.15
  - pillow=11.3
  - gdal
  - rasterio
  - shapely
  - geopandas
  - pyproj
  - fiona
  - pip:
      - affine==2.4.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.0
      - imageio==2.37.0
      - julia==0.6.2
      - juliacall==0.9.28
      - juliapkg==0.1.20
      - kiwisolver==1.4.9
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - semver==3.0.4
      - six==1.17.0
      - tomli==2.2.1
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - tzdata==2025.2